version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
    - 80:80
    networks:
      - gis_network
    volumes:
      - /home/ubuntu/nginx.conf:etc/nginx/nginx.conf
      - django_static:/data/static/
      - django_media:/data/media/


  django:
    image: gis_django:4
    networks:
      - gis_network
    volumes:
      - django_static:/home/study_ai_django2/staticfiles/
      - django_media:/home/study_ai_django2/media/

networks:
  gis_network:

volumes:
  django_static:
  django_media: